name: Cypress Tests
on:
  push:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Cypress.io
        uses: Cypress-io/github-action@v6
        with:
          start: npm start
          browser: electron
      - name: Generate HTML Report
        run: node cucumber-html-report.js
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/cucumberReports
        
