name: Cypress Tests
on:
  push:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress Tests
        run: npm start
      - name: Create report
        run: node cucumber-html-report.js
      - name: Push to gh-pages
        run: |
          git config --global user.email "dashalichman01@gmail.com"
          git config --global user.name "Daryna"
          git checkout --orphan gh-pages
          git add cypress/cucumberReports
          git commit -m "Update Cucumber Report"
          git push origin gh-pages --force
    
